spring.application.name=trainfyre-utility-service
springdoc.swagger-ui.path=/trainfyre-utility-service/swagger-ui.html

server.port=8080

# Banner
spring.banner.location=classpath:banner.txt

#Email configuration
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=