server:
  port: 8080

spring:
  application:
    name: trainfyre-utility-service
  banner:
    location: banner.txt

#    Swagger UI configuration
springdoc:
  swagger-ui:
    path: /trainfyre-utility-service/swagger-ui.html

# Logging configuration
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
