spring:
  application:
    name: TrainFyre
  banner:
    location: banner.txt

  # Mustache
  mustache:
    suffix: .html
    servlet:
      expose-request-attributes: true

  # H2 Console
  autoconfigure:
    exclude:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  # Datasource H2 en memoria
  datasource:
    url: jdbc:h2:mem:trainfyre
    driver-class-name: org.h2.Driver
    username: admin
    password:

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

# https configuration
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password

  # Sesion, de momento no se usa
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        http-only: true
        same-site: strict